# behat.yml
# example behat config - leanphp/common-dev
default:
  autoload:
    '': %paths.base%/features/bootstrap
  formatters:
    pretty: true

  extensions:
    # rmiller/behat-spec extension
    RMiller\BehatSpec\Extension\BehatSpecExtension\BehatExtension:
      path: 'bin/phpspec'
    # behat/mink-extension (via behat/mink-goutter-driver)
    Behat\MinkExtension:
      sessions:
        default:
          goutte: ~

