# phpspec.yml
# example phpspec config - leanphp/common-dev
formatter.name: pretty
suites:
    default_suite:
        namespace: LeanPHP\Common
        psr4_prefix: LeanPHP\Common

extensions:
  Cjm\PhpSpec\Extension\TypeHintedMethodsExtension: ~
  LeanPHP\PhpSpec\CodeCoverage\CodeCoverageExtension:
    format:
      - html
      - clover
    output:
      html: build/phpspec-coverage
      clover: build/phpspec-coverage.xml
  RMiller\BehatSpec\Extension\BehatSpecExtension\PhpSpecExtension: ~
  RMiller\BehatSpec\Extension\PhpSpecRunExtension\PhpSpecRunExtension:
    path: bin/phpspec
    commands: [describe, exemplify]
    config: phpspec.yml
